spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定 nacos server 的地址
        server-addr: localhost:8848
        # 指定 namespace
#        namespace: 769f8071-7ce0-40bf-a016-c50468cf49bc
        # 指定集群名称
#        cluster-name: NJ
  application:
    name: user-center