spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
  #        namespace: 769f8071-7ce0-40bf-a016-c50468cf49bc
  application:
    name: content-center
server:
  port: 8010
#user-center:
#  ribbon:
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    org.yangxin.contentcenter.feignclient.UserCenterFeignClient: debug
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule